# -*- coding: utf-8 -*-
"""Sec1_Week6_683380574-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xn_vCYP0rlfvN3HOTAR7HoY-ICi_TLeq

# Lab6.1 Simple Calculator Functions
"""

def add(a, b):
    """รับตัวเลข a และ b แล้วคืนค่าผลบวก (a + b)"""
    return a + b


def subtract(a, b):
    """รับตัวเลข a และ b แล้วคืนค่าผลลบ (a - b)"""
    return a - b


def multiply(a, b):
    """รับตัวเลข a และ b แล้วคืนค่าผลคูณ (a * b)"""
    return a * b


def divide(a, b):
    """รับตัวเลข a และ b แล้วคืนค่าผลหาร (a / b)
    ถ้า b เป็น 0 จะคืนข้อความแจ้งเตือน แทนที่จะทำให้โปรแกรมพัง
    """
    if b == 0:
        return "Error: Division by zero"
    return a / b


def power(base, exponent=2):
    """รับ base และ exponent (ค่าเริ่มต้น = 2 คือยกกำลังสอง)
    แล้วคืนค่า base ยกกำลัง exponent
    """
    return base ** exponent


def get_number(prompt):
    """รับค่าตัวเลข (float) จากผู้ใช้ พร้อมตรวจสอบความถูกต้อง"""
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("กรุณาป้อนตัวเลขให้ถูกต้อง")


def main():
    """เมนูหลักแบบ while loop ให้ผู้ใช้เลือกการดำเนินการ"""
    menu = """
==== เครื่องคิดเลขอย่างง่าย ====
1. บวก
2. ลบ
3. คูณ
4. หาร
5. ยกกำลัง
0. ออกจากโปรแกรม (Exit)
=====================================================
"""
    while True:
        print(menu)
        choice = input("เลือกเมนู (0-5): ").strip()

        if choice == "0":
            print("ออกจากโปรแกรม... ขอบคุณที่ใช้บริการ")
            break

        elif choice in ("1", "2", "3", "4"):
            num1 = get_number("ป้อนตัวเลขที่ 1: ")
            num2 = get_number("ป้อนตัวเลขที่ 2: ")

            if choice == "1":
                result = add(num1, num2)
                print(f"ผลลัพธ์: {num1} + {num2} = {result}")
            elif choice == "2":
                result = subtract(num1, num2)
                print(f"ผลลัพธ์: {num1} - {num2} = {result}")
            elif choice == "3":
                result = multiply(num1, num2)
                print(f"ผลลัพธ์: {num1} * {num2} = {result}")
            elif choice == "4":
                result = divide(num1, num2)
                print(f"ผลลัพธ์: {num1} / {num2} = {result}")

        elif choice == "5":
            base = get_number("ป้อนฐาน (base): ")
            exp_input = input("ป้อนเลขยกกำลัง (Enter เพื่อใช้ค่าเริ่มต้น = 2): ").strip()
            if exp_input == "":
                result = power(base)
                print(f"ผลลัพธ์: {base} ** 2 (default) = {result}")
            else:
                exponent = float(exp_input)
                result = power(base, exponent)
                print(f"ผลลัพธ์: {base} ** {exponent} = {result}")

        else:
            print("กรุณาเลือกเมนูที่ถูกต้อง (0-5)")


if __name__ == "__main__":
    main()

"""# Lab 6.2: การสร้าง Custom Module และการใช้ Standard Library

Part 1: สร้าง Custom Module
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile my_utils.py
# 
# def greet(name):
#     """แสดงข้อความทักทาย"""
#     print(f"Hello, {name}!")
# 
# 
# def is_prime(number):
#     """ตรวจสอบว่าตัวเลขเป็นจำนวนเฉพาะหรือไม่"""
# 
#     if number < 2:
#         return False
# 
#     for i in range(2, int(number ** 0.5) + 1):
#         if number % i == 0:
#             return False
# 
#     return True

"""Part 2: ใช้ Custom Module และ Standard Modules"""

import my_utils
import math
import random


print("====================================")
my_utils.greet("Prim")
print("====================================")

print("\n--- test is_prime() ---")
test_numbers = random.sample(range(1, 101), 10)
for n in test_numbers:
    print(f"{n} เป็นจำนวนเฉพาะหรือไม่: {my_utils.is_prime(n)}")


print("\n--- test math.sqrt() ---")
number_for_sqrt = 64
print(f"รากที่สองของ {number_for_sqrt} คือ {math.sqrt(number_for_sqrt)}")

# --- ใช้ฟังก์ชันจาก standard library: random ---
print("\n--- test random.randint() ---")
random_number = random.randint(1, 100)
print(f"สุ่มตัวเลขระหว่าง 1-100 : {random_number}")

"""# Activity 6.1: Refactoring งาน Lab ก่อนหน้า"""

# Refactor Lab 2.1: Number Classification

def check_sign(num):
    """
    ตรวจสอบว่าตัวเลขเป็นจำนวนบวก จำนวนลบ หรือศูนย์

    Parameters:
        num (int): ตัวเลขที่ต้องการตรวจสอบ

    Returns:
        str: "positive", "negative" หรือ "zero"
    """
    if num < 0:
        return "negative"
    elif num > 0:
        return "positive"
    else:
        return "zero"


def check_even_odd(num):
    """
    ตรวจสอบว่าตัวเลขเป็นเลขคู่ เลขคี่ หรือศูนย์

    Parameters:
        num (int): ตัวเลขที่ต้องการตรวจสอบ

    Returns:
        str: "even", "odd" หรือ "zero"
    """
    if num == 0:
        return "zero"
    elif num % 2 == 0:
        return "even"
    else:
        return "odd"


def classify_number(num):
    """
    ตรวจสอบคุณสมบัติของตัวเลขทั้งด้านเครื่องหมาย
    และการเป็นเลขคู่หรือเลขคี่

    Parameters:
        num (int): ตัวเลขที่ต้องการตรวจสอบ

    Returns:
        tuple: ผลการตรวจสอบเครื่องหมายและคู่/คี่
    """
    sign = check_sign(num)
    even_odd = check_even_odd(num)

    return sign, even_odd


def main():
    """
    โปรแกรมหลักสำหรับรับตัวเลขหลายตัว
    และแสดงผลการตรวจสอบแต่ละตัว
    """

    print("==============================")
    print("      NUMBER CLASSIFIER")
    print("==============================")

    # รับตัวเลขจากผู้ใช้หลายตัว
    user_input = input("Enter your numbers: ")

    # แยกตัวเลขด้วยช่องว่าง
    numbers = user_input.split()

    # เปลี่ยนข้อมูลจาก string เป็น int
    numbers = list(map(int, numbers))

    print("------------------------------")

    # ตรวจสอบตัวเลขแต่ละตัว
    for num in numbers:
        sign, even_odd = classify_number(num)

        print(
            f"{num} is {sign} and is {even_odd}"
        )

    print("------------------------------")
    print("Program finished.")


# เรียกใช้งานโปรแกรม
if __name__ == "__main__":
    main()