# -*- coding: utf-8 -*-
"""Sec1_Week2_683380574-6_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1limvPjS-HRBN_Qats03i1pfxwOxnHFVM
"""



"""Week 2 683380574-6 นางสาวจันทรณภา จอมทอง

# LAB2

2.1)รับค่าตัวเลขตรวจสอบเงื่อนไข
"""

num =input("Enter your number: ").split()
num =list(map(int,num))

print("-------------------------")

for i in num:
    if i < 0:
        sign = "negative"
    elif i > 0:
        sign = "positive"
    else:
        sign = "is zero"

    if i == 0:
        n = "zero"
    elif i % 2 == 0:
        n = "even"
    else:
        n = "is odd"
#challenge
    print(i,"is",sign,"and is",n)

print("-------------------------")

"""2.2)รับค่าอายุเเนะนำหนังตามเรตอายุ"""

age = int(input("Enter your age: "))
text = input("Do you like action movies? (y/n): ").lower()
if age < 5:
    print("You're too young for movies! Enjoy cartoons.")

elif age <= 12:
    print("Recommended: G-rated or PG-rated movies.")

elif age <= 17:
    print("Recommended: PG-13 or R-rated (with parental guidance).")

else:
    print("Recommended: Any movie rating.")

#challenge
if age >=18 and text == "y":
    print("You might enjoy the latest action blockbuster!")

"""Activity2.1)อธิบายลำดับการทำงานของ if elif else เเละ logical operators โดยพิจารณาเงื่อนไขทีละขั้นตอนเเละบอกผลลัพธ์ที่โปรเเกรมเเสดง สำหรับค่าที่กำหนดให้

ตอบ:

```
**ขั้นตอนที่ 1**: ตรวจสอบเงื่อนไขแรกที่ตรรกะ if
โปรแกรมจะพิจารณาประโยคเงื่อนไข:if temp > 20 and not is_raining
เราสามารถแยกคำนวณออกเป็น 2 ฝั่งซ้าย-ขวา

โดยยึดตัวเชื่อมหลักคือ and:
  1.ฝั่งซ้าย (temp > 20): แทนค่า 25 > 20 ซึ่งเป็น True
  2.ฝั่งขวา (not is_raining): แทนค่า not True (ตรงข้ามกับ True)
        ผลลัพธ์จึงเปลี่ยนเป็น False
นำผลลัพธ์ทั้งสองฝั่งมาเชื่อมกันด้วย and:
True and False ได้ผลลัพธ์รวมเป็น False

สรุปขั้นตอนนี้: เนื่องจากเงื่อนไขของ if เป็นเท็จ (False) โปรแกรมจึงข้ามคำสั่ง print("Perfect day for a picnic!") ไป และย้ายไปตรวจสอบเงื่อนไขถัดไปแทน



**ขั้นตอนที่ 2**: ตรวจสอบเงื่อนไขถัดมาที่ตรรกะ elif
โปรแกรมจะพิจารณาประโยคเงื่อนไข:elif temp <= 20 or is_raining:
เราแยกคำนวณออกเป็น 2 ฝั่งซ้าย-ขวา

โดยยึดตัวเชื่อมหลักคือ or:
ฝั่งซ้าย (temp <= 20): แทนค่า 25 <= 20 ซึ่งเป็น False
ฝั่งขวา (is_raining): แทนค่าแล้วได้ True ตรงๆนำผลลัพธ์ทั้งสองฝั่งมาเชื่อมกันด้วย or
(เงื่อนไขของ or ขอแค่มีฝั่งใดฝั่งหนึ่งเป็นจริง ผลลัพธ์จะเป็นจริงทันที):False or True  ได้ผลลัพธ์รวมเป็น True

สรุปขั้นตอนนี้: เนื่องจากเงื่อนไขของ elif เป็นจริง (True) โปรแกรมจึงตัดสินใจทำงานในบล็อกนี้ทันที



**ขั้นตอนที่ 3**: การทำงานในบล็อกและข้ามส่วนที่เหลือ
เมื่อเงื่อนไข elif เป็นจริงแล้ว โปรแกรมจะทำคำสั่งด้านในนั่นคือ:
print("Stay indoors or bring an umbrella.")

และเมื่อเงื่อนไขก่อนหน้าถูกทำไปแล้ว โปรแกรมจะกระโดดข้ามบล็อก else:
```

Activity2.2)สร้างเกม
"""

print("CHOOSE YOUR OWN ADVENTURE GAME")
print("คุณตื่นขึ้นมาหน้าถ้ำเเห่งหนึ่ง...")

print("เจอทางเเยก")
print("1.ซ้าย")
print("2.ขวา")
ch1 = input("ทางเลือก(1/2): ")

if ch1 == "1" :
    print(".................")
    print("คุณพบตะเกียงตกอยู่")
    print("1.เก็บ")
    print("2.ไม่เก็บ")
    ch2 = input("ทางเลือก(1/2): ")
    if ch2=="1":
        print(".................")
        print("คุณได้รับเเสงสว่าง")
        print("คุณเดินไปเรื่อยๆเเละพบกล่องใบใหญ่")
        print("1.เปิดกล่อง")
        print("2.ไม่เปิดกล่อง")
        ch3 = input("ทางเลือก(1/2): ")
        if ch3=="1":
          print(".................")
          print("คุณพบว่าในกล่องคือเงาสะท้อนของตัวคุณเอง")
          print("กล่องดูดคุณเข้าไป")
          print("คุณอยู่ที่จุดเริ่มต้น")
          print(".")
          print(".")
          print(".")
          print("Ending1: BEGIN ")
        else:
          print(".................")
          print("คุณเดินตามเเสงสว่างของตะเกียงไปเรื่อยๆ")
          print("คุณพบทางออกเเละได้รับอิสระ")
          print(".")
          print(".")
          print(".")
          print("Ending3: FREE ")
    else:
        print(".................")
        print("มืดมาก")
        print("หิน!!!")
        print("คุณสดุดก้อนหินหกล้มตาย")
        print(".")
        print(".")
        print(".")
        print("Ending2: THE END ")
else:
    print(".................")
    print("คุณเดินไปเรื่อยๆ")
    print("...")
    print("หลุม!!!")
    print("คุณอยู่ที่ก้นหลุมที่มืดสนิท")
    print("คุณจะพยายามออกจากหลุมหรือไม่")
    print("1.พยายาม")
    print("2.ไม่คุณยอมเเพ้เเล้ว")
    ch4 = input("ทางเลือก(1/2): ")
    if ch4 == "1":
          print(".................")
          print("คุณคลำรอบๆตัวคุณเเละเจอประตู")
          print("คุณเปิดประตูพบกับสถานที่ที่คุณอยากไปมากที่สุดในชีวิต")
          print(".")
          print(".")
          print(".")
          print("Ending4: TRY ")
    else:
          print(".................")
          print("....คุณนั่งคนเดียวยอมเเพ้อยู่ที่ก้นหลุม")
          print(".")
          print(".")
          print(".")
          print("Ending4: JUST TRY ")