# -*- coding: utf-8 -*-
"""Sec1_Week4_683380574-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5Lm_Cod53MJJSwRBPh7BTnUMFLRYt5R

นางสาวจันทรณภา จอมทอง 683380574-6 Sec1.

# lab4_1.py - Student Management System (List Operations)
"""

# lab4_1.py - Student Management System (List Operations)
print("--- Lab 4.1: Student Management System + (Challenge) ---")

# 1) เริ่มต้นด้วย list ว่างสำหรับเก็บชื่อนักศึกษา
student_names = []
while True:
    print("1. Add Students")
    print("2. Find a Student")
    print("3. Remove a Student")
    print("4. Sort Students")
    print("5. Count Students")
    print("6. Exit")
    print("----------------------------------------")
    ch = input(f"Enter your choice (1-5): ")


    # 2) เพิ่มนักศึกษา: รับชื่อจากผู้ใช้ 3 คน แล้ว append() เข้า list
    if ch =='1':
      print("\n[1] Add Students")
      for  i   in range(3): #กำหนดตัวแปรใน loop 👈ต้องทำ
          name = input(f"Enter student name #{i + 1}: ") #กำหนดตัวแปร 👈ต้องทำ
          student_names.append(name)

      print(f"Current list: {student_names}")

    # 3) ค้นหานักศึกษา: ใช้ 'in' เพื่อเช็คว่ามีชื่อนี้อยู่ใน list หรือไม่
    if ch =='2':
      print("\n[2] Find a Student")
      search_name = input("Enter a name to search for: ")

      if search_name in student_names: #เขียนเงื่อนไข ถ้าหากมีชื่อในลิส: 👈ต้องทำ
          position = student_names.index(search_name)
          print(f"Found '{search_name}' at index {position}")
      else:
          print(f"'{search_name}' not found in the list")

      # 4) ลบนักศึกษา: เช็คก่อนว่ามีอยู่จริงหรือไม่ (กัน error) แล้วค่อย remove()
    elif ch =='3':
      print("\n[3] Remove a Student")
      remove_name = input("Enter a name to remove: ")

      if remove_name in student_names:
          student_names.remove(remove_name) #เติมฟังก์ชัน remove(remove_name) 👈ต้องทำ
          print(f"'{remove_name}' has been removed")
      else:
          print(f"'{remove_name}' not found, nothing removed")

      print(f"Updated list: {student_names}")

      # 5) เรียงลำดับรายชื่อตามตัวอักษรด้วย sort()
    elif ch =='4':
      print("\n[4] Sort Students")
      student_names.sort() #เติมฟังก์ชันsort()
      print(f"Sorted list: {student_names}")

      # 6) นับจำนวนนักศึกษาทั้งหมดด้วย len()
    elif ch =='5':
      print("\n[5] Count Students")
      print(f"Total students: {len(student_names)}") #ใช้คำสั่งlen() หาจำนวนนักศึกษาในลิส student_names👈ต้องทำ
      # ออกจากโปรแกรม
    elif ch == '6':
        print("Goodbye!")
        break

    else:
        print("Invalid choice!")

"""# lab4_2.py - Geometric Calculations (Tuples & Immutability)"""

import math

print("--- Lab 4.2: Geometric Calculations + (Challenge) ---")
x1,y1 = map(float,input("Enter a point (x1, y1): ").split())
point1 = (x1, y1)

x2,y2 = map(float,input("Enter a point (x2, y2): ").split())
point2 = (x2, y2)
# 1) กำหนดจุดสองจุดด้วย tuple: point1 และ point2
#point1 = (3, 4) #เติมพิกัด x y ของจุด
#point2 = (6, 8)  #เติมพิกัด x y ของจุด

# 2) เข้าถึงค่าพิกัด x, y ของแต่ละจุด
print("\n[1] Access Coordinates")
print(f"Point 1: x = {point1[0]}, y = {point1[1]}") #เติมเลข 0 และ 1 ใน []
print(f"Point 2: x = {point2[0]}, y = {point2[1]}") #เติมเลข 0 และ 1 ใน []

# 3) ทดลองแก้ไขค่าใน tuple เพื่อแสดงให้เห็นว่า tuple เปลี่ยนแปลงไม่ได้ (immutable)
print("\n[2] Attempt Modification (Immutability Demonstration)")
try:
    point1[0] = 5  # บรรทัดนี้จะทำให้เกิด TypeError เพราะ tuple แก้ไขไม่ได้
except TypeError as e:
    print(f"Error trying to modify tuple: {e}")

# 4) คำนวณระยะห่างระหว่างจุดสองจุดด้วยสูตรระยะทาง
#    distance = sqrt( (x2 - x1)^2 + (y2 - y1)^2 )
print("\n[3] Calculate Distance")
distance = math.sqrt((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2) #เติมเลขตำแหน่งในลิส 0 และ 1 ใน [] ให้ถูกต้อง
print(f"Distance between point1 {point1} and point2 {point2}: {distance}")

"""# Activity 4.1: List vs. Tuple: Scenario Matching

สิ่งที่อยากให้ทำ : สถานการณ์ต่อไปนี้ แต่ละเหตุการณ์ควรใช้ list หรือ tuple เพราะอะไร

**1.ข้อมูลอุณหภูมิประจำวันที่มีการบันทึกไว้ตลอดหนึ่งสัปดาห์**
  
  **ตอบ:** List เพราะอุณหภูมิอาจมีการเพิ่ม แก้ไข หรือลบข้อมูลได้ เช่น เพิ่มอุณหภูมิของวันใหม่ หรือแก้ค่าที่บันทึกผิด

**2.ค่าสี RGB ของเฉดสีเฉพาะเฉดหนึ่ง (เช่น สีแดงคือ (255, 0, 0))**
  
  **ตอบ:** Tuple เพราะค่า RGB เป็นค่าคงที่ของสีหนึ่ง ๆ ไม่ควรเปลี่ยนแปลง เช่น สีแดงต้องมีค่า (255, 0, 0) เสมอ

**3.รายการสินค้าในรถเข็นชอปปิงที่สามารถกดเพิ่มหรือลบออกได้**
  
  **ตอบ:** List เพราะรายการสินค้าเปลี่ยนแปลงตลอดเวลา สามารถเพิ่มสินค้าใหม่หรือลบสินค้าออกจากรถเข็นได้

**4.รายชื่อวันในหนึ่งสัปดาห์เรียงตามลำดับ (จันทร์ - อาทิตย์)**

  **ตอบ:** Tuple เพราะจำนวนวันและลำดับวันเป็นข้อมูลคงที่ ไม่จำเป็นต้องแก้ไข

**5.คะแนนเก็บของนักเรียนจากการส่งงานชุดต่างๆ
ซึ่งอาจมีการอัปเดตหรือแก้ไขคะแนนในภายหลังได้**
  
  **ตอบ:** List เพราะคะแนนอาจมีการแก้ไข เพิ่มคะแนนงานใหม่ หรือปรับคะแนนในภายหลังได้

**6.พิกัด GPS ของสถานที่สำคัญหรือจุดแลนด์มาร์กที่ตั้งอยู่กับที่**

  ตอบ: Tuple เพราะพิกัด (ละติจูด, ลองจิจูด) เป็นค่าตำแหน่งเฉพาะที่ไม่ควรเปลี่ยนแปลง เช่น (13.7563, 100.5018)

# Activity 4.2: Interactive To-Do List (using List Operations)

สิ่งที่อยากให้ทำ : ให้นักเรียนพัฒนาโปรแกรมจัดการรายการสิ่งที่ต้องทำ (To-Do List) แบบข้อความ (Text-based) อย่างง่าย โดยประยุกต์ใช้ความรู้เรื่องการจัดการ List ที่ได้เรียนมา
"""

todo_list = []

while True:
    print("\n===== To-Do List =====")
    print("1. Add a task")
    print("2. View tasks")
    print("3. Mark task as complete")
    print("4. Exit")


    ch = input("Enter your choice (1-4): ")

    if ch == '1':
        task = input("Enter a task: ")
        todo_list.append(task)
        print("Task added!")

    elif ch == '2':
        print("\nYour Tasks:")

        if len(todo_list) == 0:
            print("No tasks available.")
        else:
            for i in range(len(todo_list)):
                print(f"{i + 1}. {todo_list[i]}")

    elif ch == '3':
        if len(todo_list) == 0:
            print("No tasks to complete.")
        else:
            print("\nYour Tasks:")
            for i in range(len(todo_list)):
                print(f"{i + 1}. {todo_list[i]}")

            index = int(input("Enter task number to complete: "))

            if 1 <= index <= len(todo_list):
                completed_task = todo_list.pop(index - 1)
                print(f"Completed: {completed_task}")
            else:
                print("Invalid task number.")

    elif ch == '4':
        print("Goodbye!")
        break

    else:
        print("Invalid choice!")