# -*- coding: utf-8 -*-
"""Sec1_Week3_683380574_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0JAbzx9KQ-SW_P3rFL9DSTrErGaTGpY

# **LAB 3: Control Flow: Loops:**

**Lab 3.1: โปรแกรมสร้างสูตรคูณ (Multiplication Table Generator)**

Part 1: ตารางสูตรคูณแม่เดียว (Single Number Table):
"""

num = int(input("Enter a number for its multiplication table: "))
for i in range(1, 13):
    print(f"{num} x {i} = {num * i}")

"""Part 2: ตารางสูตรคูณแบบเต็ม (Full Multiplication Grid)"""

print("12x12 Multiplication Table: ")
for i in range(1,13):
  for j in range(1,13):
    print(f"{i*j:4d}", end="\t")
  print()

"""**Lab 3.2: โปรแกรมการนับถอยหลัง & เกมทายตัวเลข (Countdown & User Guessing Game)**

Part 1: โปรแกรมตัวนับถอยหลัง (Countdown Timer):
"""

start = int(input("Enter a number to start the countdown: "))
while start >= 0 :
  print(f"{start}")
  start -= 1

print("Blast off!")

"""Part 2: เกมทายตัวเลขอย่างง่าย (Simple Guessing Game):"""

secret_number = 12
max_attempts = 5
attempts = 0

while attempts < max_attempts:
  guess = int(input(f"Guess the number({attempts+1}/{max_attempts}): "))
  attempts += 1
  if guess < secret_number :
    print(f"{guess} is too low! Try again.")
  elif guess > secret_number :
    print(f"{guess} is too high! Try again.")
  else:
    print("Congratulations! You guessed it!")
    break
else:
  print(f"Sorry, you've run out of attempts! The secret number was {secret_number}.")

"""Activity 3.1: Debugging Infinite Loops & Loop Logic Errors

"""

# Buggy Snippet A: Infinite Loop
print("Buggy Snippet A:")
counter = 0
while counter < 5:
  print(counter)
  counter += 1
print("\n")

print("Buggy Snippet B:")
# Buggy Snippet B: Incorrect Range
for i in range(1, 6): # Goal: print 1, 2, 3, 4, 5
  print(i)
print("\n")

print("Buggy Snippet C:")
# Buggy Snippet C: Misplaced Break
for char in "hello":
    if char == 'l':
        print("Found 'l', skipping!")
        continue
    print(char) # This will print 'h', 'e', 'l' then break

"""Activity 3.2: Pattern Printing with Nested Loops

"""

print("1.A square of asterisks")
size=5
for i in range(size):
  for j in range(size):
    print("*",end="")
  print()
print("2.A right-angled triangle of asterisks")
for i in range(1,size+1):
  for j in range(i):
    print("*",end="")
  print()
print("3.Challenge: An inverted right-angled triangle or a pyramid.")
size = 5
for i in range(1, size + 1):
    # พิมพ์ช่องว่างนำหน้าเพื่อจัดกึ่งกลาง
    print(" " * (size - i), end="")
    # พิมพ์ดอกจัน (จำนวนคี่: 1, 3, 5, 7, 9)
    print("*" * (2 * i - 1))