# -*- coding: utf-8 -*-
"""Sec1_Week5_683380574_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSOvzBC8Kc7HWw3TjaUHBt-Ty4aTjc7B
"""

# ============================================================
# เติมโค้ด: Lab 5.1 - Simple Contact Book Manager (Dictionary Focus)
# ------------------------------------------------------------
# โจทย์: สร้างระบบจัดการสมุดโทรศัพท์แบบ Text-based โดยใช้ Dictionary
#
# คำใบ้ (ทบทวนจากบทเรียน):
#   - สร้าง Dictionary ว่าง: contacts = {}
#   - เพิ่ม/แก้ไขข้อมูล: contacts[key] = value
#   - อ่านข้อมูลอย่างปลอดภัย: contacts.get(key)
#   - วนลูปอ่านทั้ง key และ value: for key, value in contacts.items():
#   - ลบข้อมูล: contacts.pop(key, default) หรือ del
# ============================================================

# --- ข้อที่ 1: สร้าง Dictionary ว่างสำหรับเก็บข้อมูลผู้ติดต่อ ---
# todo (1): สร้าง dictionary ว่างชื่อ contacts
contacts = {}

while True:
    # แสดงเมนูตัวเลือก
    print("\n=== Contact Book Manager ===")
    print("1. Add/Update Contact")
    print("2. View Contact Details")
    print("3. List All Contacts")
    print("4. Delete Contact")
    print("5. Exit")

    choice = input("Enter choice (1-5): ")

    # --- เมนูที่ 1: เพิ่มหรืออัปเดตข้อมูลผู้ติดต่อ ---
    if choice == '1':
        name = input("Enter contact name: ").lower() #Challenge
        phone = input("Enter phone number: ")
        email = input("Enter email: ")

        # todo (2): เก็บข้อมูลลงใน contacts โดยใช้ name เป็น key
        # และ value เป็น dictionary ที่เก็บข้อมูล "phone" และ "email"
        contacts[name] = {
            "phone": phone,
            "email": email
        }
        print(f"Contact '{name}' saved successfully!")

    # --- เมนูที่ 2: ดูรายละเอียดผู้ติดต่อ ---
    elif choice == '2':
        name = input("Enter contact name to view: ")

        # todo (3): ใช้เมธอด .get() เพื่อดึงข้อมูลของผู้ติดต่อตามชื่อ name
        info = contacts.get(name)

        if info:
            print(f"\nName: {name}")
            print(f"Phone: {info['phone']}")
            print(f"Email: {info['email']}")
        else:
            print("Contact not found.")

    # --- เมนูที่ 3: แสดงรายการผู้ติดต่อทั้งหมด ---
    elif choice == '3':
        if not contacts:
            print("No contacts available.")
        else:
            print("\n--- All Contacts ---")
            # todo (4): ใช้เมธอด .items() วนลูปเพื่อดึงชื่อ (key) และรายละเอียด (value)
            for name, details in contacts.items():
                print(f"Name: {name} | Phone: {details['phone']} | Email: {details['email']}")

    # --- เมนูที่ 4: ลบข้อมูลผู้ติดต่อ ---
    elif choice == '4':
        name = input("Enter contact name to delete: ")


        # todo (5): ใช้เมธอด .pop() ลบ key ตามชื่อ name
        # และใส่ค่า default เป็น None หากไม่พบชื่อเพื่อป้องกันการเกิด Error
        removed_contact = contacts.pop(name, None)

        if removed_contact:
            print(f"Contact '{name}' deleted successfully!")
        else:
            print("Contact not found.")

    # --- เมนูที่ 5: ออกจากโปรแกรม ---
    elif choice == '5':
        print("Exiting Contact Book Manager. Goodbye!")
        # todo (6): เขียนคำสั่งเพื่อหยุดการทำงานของ while loop
        break

    else:
        print("Invalid choice! Please enter a number from 1 to 5.")

"""Lab 5.1 Challenge: Ensure keys are case-insensitive when searching or deleting (convert user input to .lower() or .title() consistently)."""

# ============================================================
# 🔧 เติมโค้ด: Lab 5.2 - Course Enrollment & Collaboration (Set Focus)
# ------------------------------------------------------------
# โจทย์: จำลองการลงทะเบียนเรียนและใช้ Set Operations ในการเปรียบเทียบรายชื่อนักศึกษา
#
# คำใบ้ (ทบทวนจากบทเรียน):
#   - intersection() หรือ &  : หาองค์ประกอบที่มีร่วมกันทั้งสองกลุ่ม
#   - union() หรือ |         : รวมองค์ประกอบทั้งหมดโดยลบตัวซ้ำให้อัตโนมัติ
#   - difference() หรือ -    : หาองค์ประกอบที่มีในกลุ่มแรกแต่ไม่มีในกลุ่มสอง
#   - symmetric_difference() หรือ ^ : หาองค์ประกอบที่มีในกลุ่มใดกลุ่มหนึ่งเท่านั้น (ไม่นับตัวที่ซ้ำกัน)
#   - set(list_name)         : แปลง List ให้เป็น Set เพื่อขจัดข้อมูลที่ซ้ำกัน
# ============================================================

# --- ข้อที่ 1 & 2: กำหนด Set ของนักศึกษาในแต่ละรายวิชา ---
# กำหนดเซตของนักศึกษาวิชา Python และ Java
python_students = {"S001", "S003", "S005", "S007", "S009"}
java_students = {"S002", "S003", "S006", "S007", "S010"}

print(f"Python Students: {python_students}")
print(f"Java Students:   {java_students}\n")


# --- ข้อที่ 3: หานักศึกษาที่เรียนทั้ง 2 วิชา (Intersection) ---
# todo (1): ใช้เมธอด .intersection() หรือเครื่องหมาย & เพื่อหานักศึกษาที่ลงเรียนทั้ง Python และ Java
both_courses = python_students.intersection(java_students)
print(f"Students in Both Courses: {both_courses}")


# --- ข้อที่ 4: หานักศึกษาทั้งหมดแบบไม่ซ้ำกัน (Union) ---
# todo (2): ใช้เมธอด .union() หรือเครื่องหมาย | เพื่อหารายชื่อนักศึกษาทั้งหมดจากทั้งสองวิชา
all_unique_students = python_students.union(java_students)
print(f"All Unique Students: {all_unique_students}")


# --- ข้อที่ 5: หานักศึกษาที่เรียนเฉพาะวิชา Python เท่านั้น (Difference) ---
# todo (3): ใช้เมธอด .difference() หรือเครื่องหมาย - เพื่อหานักศึกษาที่เรียน Python แต่ไม่ได้เรียน Java
only_python = python_students.difference(java_students)
print(f"Students Only in Python: {only_python}")


# --- ข้อที่ 6: หานักศึกษาที่เรียนเพียงวิชาใดวิชาหนึ่งเท่านั้น (Symmetric Difference) ---
# todo (4): ใช้เมธอด .symmetric_difference() หรือเครื่องหมาย ^ เพื่อหานักศึกษาที่ไม่ได้เรียนซ้ำทั้งสองวิชา
exclusive_students = python_students.symmetric_difference(java_students)
print(f"Students in Only One Course: {exclusive_students}\n")


# --- ข้อที่ 7: การลบข้อมูลซ้ำออกจาก List ---
all_students_list = ["S001", "S003", "S005", "S001", "S002"]
print(f"Original List (with duplicates): {all_students_list}")

# todo (5): แปลง all_students_list ให้เป็น set เพื่อลบตัวซ้ำ แล้วแปลงกลับเป็น list
unique_students_list = list(set(all_students_list))
print(f"Unique List (after removing duplicates): {unique_students_list}")

"""---

## รายละเอียดกิจกรรม (Detailed Activities)

### กิจกรรมที่ 5.1: การประยุกต์ใช้ Dictionary และ Set ในชีวิตจริง

* **รูปแบบ:** กิจกรรมระดมความคิด (กลุ่มย่อย หรือ ทั้งชั้นเรียน)
* **คำชี้แจง:** ให้นักเรียนช่วยกันยกตัวอย่างสถานการณ์หรือปัญหาในชีวิตจริงที่ **Dictionary** และ **Set** เหมาะสมจะถูกนำมาใช้เป็นโครงสร้างข้อมูล พร้อมอธิบายเหตุผลประกอบ
* **คำถามกระตุ้นความคิด (Prompts):**
* คุณจะนำ **Dictionary** ไปใช้ตรงไหนในเกมได้บ้าง? *(เช่น ช่องเก็บของของผู้เล่น (Inventory), ค่าพลังของตัวละคร)*
* **Dictionary** จะช่วยจัดเก็บข้อมูลสินค้าในร้านค้าออนไลน์ได้อย่างไร? *(เช่น ข้อมูลรายละเอียดสินค้าโดยใช้อ้างอิงจากรหัสสินค้า/ID)*
* **Set** จะมีประโยชน์อย่างไรในการจัดการสิทธิ์ของผู้ใช้ หรือการจัดการแท็ก? *(เช่น บทบาทสิทธิ์ใช้งานที่ไม่ซ้ำกัน, แฮชแท็กที่ไม่ซ้ำกัน)*
* นึกออกไหมว่ามีสถานการณ์ไหนบ้างที่เราต้องเช็กอย่างรวดเร็วว่า **"มีข้อมูลนี้อยู่ในกลุ่มข้อมูลขนาดใหญ่หรือไม่"** โดยไม่สนใจลำดับก่อนหลัง? *(เช่น รายชื่อ IP Address ที่ถูกบล็อก, การนับจำนวนผู้เข้าชมเว็บที่ไม่นับคนซ้ำ)*


* **วัตถุประสงค์:** เพื่อเสริมสร้างความเข้าใจในการนำไปประยุกต์ใช้จริง และส่งเสริมการคิดวิเคราะห์ในการเลือกใช้โครงสร้างข้อมูลให้เหมาะสม

---

### กิจกรรมที่ 5.2: โปรแกรมนับความถี่ของคำ (Word Frequency Counter) โดยใช้ Dictionary

* **รูปแบบ:** โจทย์ท้าทายการเขียนโค้ดรายบุคคล (Individual coding challenge)
* **คำชี้แจง:** ให้นักเรียนเขียนโปรแกรมรับข้อความ (ประโยค) จากผู้ใช้ แล้วนับจำนวนความถี่ของแต่ละคำโดยใช้ Dictionary
* **ขั้นตอนการทำงาน (Steps):**
1. รับข้อความประโยคจากผู้ใช้
2. แปลงข้อความให้เป็นตัวพิมพ์เล็กทั้งหมด: `sentence.lower()`
3. แยกประโยคออกเป็นคำๆ: `words = sentence.split()`
4. กำหนด Dictionary เปล่าขึ้นมา: `word_counts = {}`
5. วนลูปอ่านคำแต่ละคำในลิสต์ `words`
6. ภายในลูป ใช้ `if word in word_counts:` เพื่อเช็กว่าคำนั้นมีอยู่ใน Key ของ Dictionary แล้วหรือยัง
7. ถ้า **มีแล้ว** ให้เพิ่มค่าจำนวนนับขึ้นอีก 1: `word_counts[word] += 1`
8. ถ้า **ยังไม่มี** ให้เพิ่มคำนั้นเข้า Dictionary พร้อมกำหนดค่าเริ่มต้นเป็น 1: `word_counts[word] = 1`
9. แสดงผลลัพธ์ของ Dictionary `word_counts`


* **ความท้าทายเพิ่มเติม (Challenge):** ให้จัดการกับเครื่องหมายวรรคตอนด้วย *(เช่น ลบเครื่องหมายจุลภาค `,` หรือจุด `.` ออกก่อนนำคำไปนับ)* **คำใบ้:** ใช้คำสั่ง `word.strip('.,!?"')`
* **วัตถุประสงค์:** เพื่อประยุกต์ใช้การทำงานของ Dictionary กับโจทย์การประมวลผลข้อความจริง แสดงให้เห็นถึงประสิทธิภาพในการนับและการค้นหาข้อมูล
"""

#กิจกรรมที่ 5.1: การประยุกต์ใช้ Dictionary และ Set ในชีวิตจริง

  #1.คุณจะนำ Dictionary ไปใช้ตรงไหนในเกมได้บ้าง?

  #ช่องเก็บของ (Inventory) โดยใช้ชื่อไอเทมหรือรหัสไอเท็มเป็น Key และจำนวนเป็น Value

inventory = {
    "Potion": 10,
    "Sword": 1,
    "Shield": 1
}

  #ค่าพลังของตัวละคร (Character Stats)

player = {
    "HP": 100,
    "MP": 50,
    "Level": 12,
    "Gold": 500
}

#เหตุผล: Dictionary เหมาะกับการเก็บข้อมูลที่มี Key และ Value ทำให้ค้นหาหรือแก้ไขข้อมูลได้สะดวกและรวดเร็ว

  #2.Dictionary จะช่วยจัดเก็บข้อมูลสินค้าในร้านค้าออนไลน์ได้อย่างไร?

  #ใช้รหัสสินค้า (Product ID) เป็น Key และรายละเอียดสินค้าเป็น Value

products = {
    "P001": {
        "name": "Laptop",
        "price": 25000,
        "stock": 10
    },
    "P002": {
        "name": "Mouse",
        "price": 450,
        "stock": 30
    }
}

#เหตุผล: สามารถค้นหาสินค้าได้อย่างรวดเร็วจากรหัสสินค้า และจัดเก็บรายละเอียดหลายรายการไว้ในที่เดียว


  #3.Set จะมีประโยชน์อย่างไรในการจัดการสิทธิ์ของผู้ใช้ หรือการจัดการแท็ก?

  #เก็บสิทธิ์ของผู้ใช้

permissions = {"Read", "Write", "Delete"}

  #เก็บแท็กหรือแฮชแท็ก

hashtags = {"python", "coding", "AI"}

#เหตุผล: Set จะไม่เก็บข้อมูลซ้ำ จึงเหมาะสำหรับข้อมูลที่ต้องมีค่าไม่ซ้ำกัน และสามารถตรวจสอบการมีอยู่ของข้อมูลได้รวดเร็ว

  #4.มีสถานการณ์ไหนที่ต้องตรวจสอบอย่างรวดเร็วว่ามีข้อมูลอยู่หรือไม่ โดยไม่สนใจลำดับ?

  #รายชื่อ IP Address ที่ถูกบล็อก

blocked_ips = {
    "192.168.1.1",
    "10.0.0.1",
    "172.16.0.5"
}

  #รายชื่อผู้เข้าชมเว็บไซต์ที่ไม่ซ้ำ

visitors = {
    "user001",
    "user002",
    "user003"
}
  #รายชื่อนักศึกษาที่ลงทะเบียนเรียนแล้ว

#เหตุผล: Set ช่วยให้ตรวจสอบได้อย่างรวดเร็วว่าข้อมูลมีอยู่หรือไม่ และไม่ต้องกังวลเรื่องข้อมูลซ้ำ

#กิจกรรมที่ 5.2: โปรแกรมนับความถี่ของคำ (Word Frequency Counter) โดยใช้ Dictionary

input_sentence = input("Please Enter a sentence: ")
# แปลงให้เป็นตัวพิมพ์เล็กทั้งหมด
sentence = input_sentence.lower()
# แยกประโยคออกเป็นคำๆ
words = sentence.split()
# กำหนด Dictionary เปล่าขึ้นมา
word_counts = {}
# วนลูปอ่านคำแต่ละคำในลิสต์
for w in words:
    # Challenge จัดการกับเครื่องหมายวรรคตอน
    w = w.strip('.,!?"')
    # ถ้าคำนั้นมีอยู่ใน Key ของ Dictionary แล้ว
    if w in word_counts:
        # ให้เพิ่มค่าจำนวนนับขึ้นอีก 1
        word_counts[w] += 1
    else:
        # ถ้ายังไม่มี ให้เพิ่มคำนั้นเข้า Dictionary พร้อมกำหนดค่าเริ่มต้นเป็น 1
        word_counts[w] = 1
# แสดงผลลัพธ์ของ Dictionary
print(word_counts)

"""# ในส่วนของ LAB เป็นแบบฝึกหัดเพื่อเติมส่วนที่ขาดหายไป

#ยังไม่มีส่วนของ LAB Challenge นะครับ ต้องเขียนเพิ่ม

# ***ก็ทำทั้ง LAB และ Activity เพื่อคะแนนเต็มและเซฟ A  นะครับ (ยังไม่รวมสอบ)***
"""